// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uaygagneznpwilhaavuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVheWdhZ25lem5wd2lsaGFhdnVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3MjcwNjUsImV4cCI6MjA5MDMwMzA2NX0.msLLxU4Hhdowx6PykvkXG5MxsGI0PXHm4kI4Vu6DDII";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});